version: '3.8'

services:
  web:
    build:
      context: ./mompopcafe
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    build:
      context: ./mompopdb
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "Msois@123"
      MYSQL_DATABASE: "mom_pop_db"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "Msois@123"
    ports:
      - "3306:3306"
    volumes:
      - ./mompopdb/sql:/docker-entrypoint-initdb.d
